apiVersion: v1
kind: Pod
metadata:
  name: router
  labels:
    app: router
spec:
  containers:
  - name: router
    image: darkmessiah/swan:0.0.10
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "3650d"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
  restartPolicy: Always
